### ISSUE TITLE
OVA Request(s)

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [ubnetdef/Lockdown-v7#2]
Greetings!

I'm requesting all of the OVAs. I'm trying to recreate the Lockdown Environment for learning purposes with my team. If you can send me what you have, that'd be awesome.

PS, ya'll rocked it out this competition. Thanks for all the learning.

**Comment by L1ghtman2k** [comment]
That is possible, and while I am downloading all of the OVAs from vCenter, I will make a couple of notes about the VMs for this Lockdown:

- Fedora, Mint, and Elementary had their `/etc/*-release` files changed on a template level. This is because those operating systems are not officially compatible with VMware tools even though things like networking in Mint and Elementary work just like in Ubuntu(which VMware tools do support). By changing `/etc/*-release` we are essentially tricking vmware tools to think that they are working with regular Ubuntus/RHELs, which allows us to change things like hostname, ip/netmask/gateway addresses, and more. Ansible fixes those files after VMware tools assign static IP addresses to those VMs [here](https://github.com/ubnetdef/Lockdown-v7/blob/5b7b66b53b2468b678a5867bfb29df740eea6cfe/deploy.yaml#L31-L58). Thus if you are not using ansible, you may need to fix those files


- The bulk of the work to install services is done by Ansible, so we did not include services (except for FTP) into the templates. This requires our ansible instance to be in a network that can reach both vCenter(for template deployment) and VMs(for service deployment). This is just something extra in case you are planning to deploy the entire infra using Ansible. 

More on black team notes: https://wiki.ubnetdef.org/guides/lockdown_black_team

OVAs will be uploaded within the next couple days

Thank you for participating, we are glad that you liked Lockdown :D

**Comment by ChrisFischer-MTA** [comment]
Great, thanks so much for addressing this. 

I wanted to follow up with asking, the OVAs include the "malicious services" we saw in competition, correct?
Additionally, what was the scoring engine used in the competition?
Is it possible to get the red team scripts or the powerpoint they gave post competition?

Thanks so much, black team.

**Comment by L1ghtman2k** [comment]
Not exactly, those snapshots are clean, and the reason is Red Team sometimes brings the malware that they would look to keep private. Everything they would like to announce would either reside in their GitHub like https://github.com/ritsec or on RedTeam slides. You could recreate the malicious services that Red Team decided to make public by redeploying those tools yourself

Following is the scoring engine used for the competition https://github.com/ubnetdef/scoreengine2

The red team powerpoint will be soon emailed to the teams that have competed

**Comment by ChrisFischer-MTA** [comment]
OK, great! So I won't have linux instances calling back to some C2 service somewhere. That's perfect, actually. Thanks so much for your help. I look forward to the OVAs.

**Comment by L1ghtman2k** [comment]
Here are the OVAs for Lockdown v7:
https://buffalo.box.com/s/lpe7bzncmaxsgjyhrcp09d7wb0nhspee
